#!/usr/bin/env bash
# MCPilot Lineage Investigator - Quick Start Guide

echo "🚀 MCPilot Lineage Investigator - Natural Language Enhanced"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 What Was Added:"
echo "  ✓ Natural Language Question Parser"
echo "  ✓ /lineage-api/ask endpoint (POST)"
echo "  ✓ Completely redesigned UI with question input"
echo "  ✓ Tabbed results interface"
echo "  ✓ Parsed intent visualization"
echo ""
echo "🎯 How to Use:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Start the API (if not already running):"
echo "   $ uvicorn apps.graphrag_api.app:app --reload --port 8000"
echo ""
echo "2. Open in browser:"
echo "   http://localhost:8000/lineage"
echo ""
echo "3. Ask a question (examples):"
echo "   • 'What's the balance for account 102?'"
echo "   • 'Show transactions for customer Asha Patel'"
echo "   • 'Why is account 105 balance different?'"
echo "   • 'List all fees for customer 103'"
echo ""
echo "4. View results across tabs:"
echo "   • Investigation Results (metrics, narrative, lineage)"
echo "   • Queries & Results (generated SQL)"
echo "   • Detailed Analysis (row-level diffs)"
echo "   • Sample Tables (database previews)"
echo ""
echo "💻 API Testing:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Using curl:"
echo '  curl -X POST http://localhost:8000/lineage-api/ask \'
echo '    -H "Content-Type: application/json" \'
echo '    -d '"'"'{"question": "Show balance for account 102"}'"'"
echo ""
echo "Using Python:"
echo '  import requests'
echo '  response = requests.post('
echo '    "http://localhost:8000/lineage-api/ask",'
echo '    json={"question": "What is the balance for account 102?"}'
echo '  )'
echo '  print(response.json())'
echo ""
echo "📁 Key Files Modified/Created:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "New:"
echo "  • core/lineage/question_parser.py (Natural language parser)"
echo "  • LINEAGE_ENHANCEMENTS.md (Detailed documentation)"
echo "  • ENHANCEMENT_SUMMARY.md (This summary)"
echo ""
echo "Modified:"
echo "  • apps/graphrag_api/app.py (Added /lineage-api/ask endpoint)"
echo "  • ui/lineage/index.html (Complete UI redesign)"
echo "  • ui/lineage/app.js (Rewritten for natural language)"
echo ""
echo "Unchanged (but compatible):"
echo "  • ui/lineage/styles.css (Existing CSS works perfectly)"
echo "  • core/lineage/lineage_router.py (Backend unchanged)"
echo ""
echo "📚 Documentation:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  • LINEAGE_ENHANCEMENTS.md - Comprehensive feature guide"
echo "  • ENHANCEMENT_SUMMARY.md - Technical overview"
echo "  • ARCHITECTURE.md - System architecture (existing)"
echo ""
echo "🔧 Extending the Parser:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Edit core/lineage/question_parser.py and add synonyms:"
echo ""
echo "  ENTITY_SYNONYMS = {"
echo "      'account': ['account', 'acct', 'bank account', 'checking', 'savings'],"
echo "      'customer': ['customer', 'client', 'user', 'person'],"
echo "      # Add more entity types and synonyms here"
echo "  }"
echo ""
echo "✨ Features:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  ✓ Free-text natural language input"
echo "  ✓ Intelligent intent recognition"
echo "  ✓ Entity identifier extraction"
echo "  ✓ Semantic synonym understanding"
echo "  ✓ Date range detection (optional)"
echo "  ✓ Confidence scoring for parsed intent"
echo "  ✓ Full transparency (queries shown)"
echo "  ✓ Results export to CSV"
echo "  ✓ AI-generated narrative explanations"
echo "  ✓ Lineage visualization"
echo "  ✓ Backward compatible (old API still works)"
echo ""
echo "🎓 Example Questions:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Account Focused:"
echo "  • Show balance for account 102"
echo "  • What's the account balance?"
echo "  • Account 105 has discrepancies?"
echo "  • Display account 201 details"
echo ""
echo "Customer Focused:"
echo "  • Show balance for customer Asha Patel"
echo "  • Transactions for John Doe"
echo "  • Customer 103 account list"
echo "  • What fees do clients have?"
echo ""
echo "Metric Focused:"
echo "  • Total transactions for account 102"
echo "  • How much in fees?"
echo "  • Balance discrepancies"
echo "  • All inflows for customer"
echo ""
echo "Date Range:"
echo "  • Transactions from 2024-01-01 to 2024-12-31"
echo "  • Balance last 30 days"
echo "  • Q4 2024 activity"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Ready to investigate? Go to http://localhost:8000/lineage"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
